### PR TITLE
Release 1.1.8

### PR DESCRIPTION
**Pull request by machacekondra**
Change-Id: I25675b58300e8c1185f595051363ec26d247bde6
Signed-off-by: Ondra Machacek <omachace@redhat.com>

### CODE REVIEW

**Comment by machacekondra** [comment]
ci build please

**Comment by mykaul** [comment]
Is there some changelog for the release? I don't see milestones used in this project, and PRs/issues are not tagged with anything that can help identify.

**Comment by machacekondra** [comment]
Changelog is in the spec file. I may add this changelog also to release on github page, which may be usefull for galaxy.

**Comment by mwperina** [comment]
> Changelog is in the spec file. I may add this changelog also to release on github page, which may be usefull for galaxy.

+1

**Pull request merged**
