### PR TITLE
Add support for log and tmp disks.

### PR DESCRIPTION
**Pull request by ghost**
CloudForms requires a single extra disk for its database. However, it can be configured to use separate disks for logs and temporary files, using the `-l` and `-t` options of `appliance_console_cli`. This PR aims at providing additional tasks to configure these disks.

This PR also fixes a small with the admin password setup. The `failed_when` check was not using the correct registered variable and generated an error.

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by ghost** [comment]
@machacekondra, @mwperina, could you please review this PR ?

**Review by machacekondra — APPROVED** [review]
Thanks for the patch, looks OK, I just have two general comments:

1) any reason using dictionary like:
```yaml
disks:
  database:
    name: xx
    ...
  tmp:
    name: yy
    ...
```

This dict structure breaks backward compatibility, as we used list before.
instead of list as it was before:

```yaml
disks:
  - name: xx
    type: database
    ...
  - name: yy
    type: tmp
```

2) I wonder whether it would be more maintainble to write a filter which will produce proper `miq_int_cmd `based on the passed variables... The logic in `tasks/cfme_identify_disk_device.yml` looks quite complex and in python code could be simpler.

**Comment by ghost** [comment]
I use a dictionary to be able to loop over the keys. The keys become `item` in the loops. But it's more a habit than a strong opinion :)

The idea of generating the command is good. Wouldn't it be a module, rather than a filter ? Maybe in another PR ?

**Comment by machacekondra** [comment]
> The idea of generating the command is good. Wouldn't it be a module, rather than a filter ? Maybe in another PR ?

Right, module would be actually better. Ok merging.

**Pull request merged**
